//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kvantorium
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kvantorium_dostizheniyaEntities1 : DbContext
    {
        public kvantorium_dostizheniyaEntities1()
            : base("name=kvantorium_dostizheniyaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<award_table> award_table { get; set; }
        public virtual DbSet<direction_table> direction_table { get; set; }
        public virtual DbSet<level_table> level_table { get; set; }
        public virtual DbSet<mentor_table> mentor_table { get; set; }
        public virtual DbSet<participant_table> participant_table { get; set; }
        public virtual DbSet<subdivision_table> subdivision_table { get; set; }
    }
}
